# Generated by Django 4.0.6 on 2022-08-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Atletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('idade', models.IntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('competicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cob.competicao')),
            ],
        ),
    ]
